[build]
  publish = "dist"
  command = "npm install && npm run build"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

